"""
Email digest - send daily summary of top news
"""
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import List, Dict


def create_digest_html(articles: List[Dict], raises: List[Dict]) -> str:
    """Create HTML email digest"""
    funding_articles = [a for a in articles if a.get("is_funding")][:10]
    regulatory_articles = [a for a in articles if a.get("is_regulatory")][:10]
    top_raises = raises[:10]

    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; }}
            h1 {{ color: #1a1a2e; }}
            h2 {{ color: #16213e; border-bottom: 2px solid #e94560; padding-bottom: 5px; }}
            .article {{ margin: 10px 0; padding: 10px; background: #f5f5f5; border-radius: 5px; }}
            .source {{ color: #666; font-size: 12px; }}
            .amount {{ color: #0f4c75; font-weight: bold; }}
            a {{ color: #e94560; text-decoration: none; }}
            a:hover {{ text-decoration: underline; }}
        </style>
    </head>
    <body>
        <h1>Frontier Tech Daily Digest</h1>
        <p style="color: #666;">{datetime.now().strftime('%B %d, %Y')}</p>

        <h2>Crypto Funding Rounds (DefiLlama)</h2>
    """

    if top_raises:
        for r in top_raises:
            investors = ", ".join(r.get("lead_investors", [])[:2]) or "Undisclosed"
            html += f"""
            <div class="article">
                <strong>{r['project']}</strong> - <span class="amount">{r['amount']}</span> ({r['round']})
                <br><span class="source">Led by: {investors} | {r['category']}</span>
            </div>
            """
    else:
        html += "<p>No new raises in the past week.</p>"

    html += "<h2>Funding News</h2>"
    if funding_articles:
        for a in funding_articles:
            html += f"""
            <div class="article">
                <a href="{a['link']}">{a['title']}</a>
                <br><span class="source">{a['source']} | {a['published'][:10]}</span>
            </div>
            """
    else:
        html += "<p>No funding news today.</p>"

    html += "<h2>Regulatory & Industry News</h2>"
    if regulatory_articles:
        for a in regulatory_articles:
            html += f"""
            <div class="article">
                <a href="{a['link']}">{a['title']}</a>
                <br><span class="source">{a['source']} | {a['published'][:10]}</span>
            </div>
            """
    else:
        html += "<p>No regulatory news today.</p>"

    html += """
        <hr>
        <p style="color: #999; font-size: 11px;">Generated by your News Aggregator</p>
    </body>
    </html>
    """
    return html


def send_digest_email(articles: List[Dict], raises: List[Dict]):
    """Send the digest email via Gmail SMTP"""
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    recipients = os.getenv("EMAIL_RECIPIENTS", "").split(",")

    if not all([sender, password, recipients[0]]):
        print("Email not configured - skipping send")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Frontier Tech Digest - {datetime.now().strftime('%b %d')}"
    msg["From"] = sender
    msg["To"] = ", ".join(recipients)

    html_content = create_digest_html(articles, raises)
    msg.attach(MIMEText(html_content, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipients, msg.as_string())
        print(f"Digest sent to {len(recipients)} recipients")
    except Exception as e:
        print(f"Error sending email: {e}")


if __name__ == "__main__":
    # Test with sample data
    sample_articles = [{
        "title": "Test Funding Article",
        "link": "https://example.com",
        "source": "test",
        "published": "2024-01-01T12:00:00",
        "is_funding": True,
        "is_regulatory": False,
    }]
    sample_raises = [{
        "project": "TestProject",
        "amount": "$10M",
        "round": "Seed",
        "lead_investors": ["a]6z"],
        "category": "DeFi",
        "date": "2024-01-01",
    }]

    html = create_digest_html(sample_articles, sample_raises)
    with open("test_digest.html", "w") as f:
        f.write(html)
    print("Test digest written to test_digest.html")
